-- Add maintenance-order schema foundation for hotel MO/PM dashboards.
-- Follows the existing IM/JO storage patterns while introducing dedicated MO tables.

alter type public.module_code add value if not exists 'mo';

create table if not exists public.mo_dashboard_json (
  id uuid default gen_random_uuid() not null primary key,
  organization_id uuid not null,
  upload_job_id uuid not null unique,
  schema_version text not null,
  generated_json jsonb not null,
  generated_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mo_dashboard_json_upload_job_id_fkey
    foreign key (upload_job_id) references public.upload_jobs(id) on delete cascade
);

create table if not exists public.mo_records (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  upload_job_id uuid not null,
  uploaded_file_id uuid,
  source_row_id bigint,
  chain_code text,
  hotel_code text,
  module_code text,
  country_code text,
  created_datetime timestamptz,
  job_status text,
  job_order text,
  guest_name text,
  location text,
  category text,
  defect text,
  remarks text,
  deadline_datetime timestamptz,
  completed_datetime timestamptz,
  escalation_level text,
  escalation_to text,
  building text,
  floor text,
  asset text,
  created_by text,
  created_by_department text,
  assigned_to text,
  completed_by text,
  inspected_by text,
  attachment text,
  checklist_name text,
  checklist_status text,
  stock_out_by text,
  stock_out_qty text,
  inventory_item text,
  comment text,
  remarks_proof_of_completion text,
  e_signature text,
  inspection_remark text,
  inspection_result text,
  guest_related text,
  cancel_reason text,
  stop_reason text,
  type text not null,
  is_completed boolean not null default false,
  is_cancelled boolean not null default false,
  is_stopped boolean not null default false,
  is_open boolean not null default false,
  is_overdue boolean not null default false,
  is_escalated boolean not null default false,
  is_guest_related boolean not null default false,
  has_attachment boolean not null default false,
  has_checklist boolean not null default false,
  has_inventory_usage boolean not null default false,
  has_esignature boolean not null default false,
  has_inspection boolean not null default false,
  inspection_passed boolean not null default false,
  inspection_failed boolean not null default false,
  resolution_minutes numeric,
  sla_minutes numeric,
  deadline_variance_minutes numeric,
  completed_within_sla boolean not null default false,
  created_date date,
  created_hour integer,
  created_week text,
  created_month text,
  created_quarter text,
  completed_date date,
  stock_out_qty_num numeric,
  escalation_level_num numeric,
  normalized_row jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mo_records_upload_job_id_fkey
    foreign key (upload_job_id) references public.upload_jobs(id) on delete cascade,
  constraint mo_records_uploaded_file_id_fkey
    foreign key (uploaded_file_id) references public.uploaded_files(id)
);

create table if not exists public.mo_staging_rows (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  upload_job_id uuid not null,
  uploaded_file_id uuid not null,
  row_number integer not null,
  raw_row jsonb not null,
  parse_error text,
  is_valid boolean not null default true,
  created_at timestamptz not null default now(),
  constraint mo_staging_rows_upload_job_id_fkey
    foreign key (upload_job_id) references public.upload_jobs(id) on delete cascade,
  constraint mo_staging_rows_uploaded_file_id_fkey
    foreign key (uploaded_file_id) references public.uploaded_files(id) on delete cascade
);

create index if not exists mo_dashboard_json_created_idx
  on public.mo_dashboard_json (created_at);

create index if not exists mo_dashboard_json_job_idx
  on public.mo_dashboard_json (upload_job_id);

create index if not exists mo_records_asset_idx
  on public.mo_records (asset);

create index if not exists mo_records_building_idx
  on public.mo_records (building);

create index if not exists mo_records_category_idx
  on public.mo_records (category);

create index if not exists mo_records_created_datetime_idx
  on public.mo_records (created_datetime);

create index if not exists mo_records_job_idx
  on public.mo_records (upload_job_id);

create index if not exists mo_records_job_order_idx
  on public.mo_records (job_order);

create index if not exists mo_records_scope_idx
  on public.mo_records (chain_code, hotel_code, module_code, country_code);

create index if not exists mo_records_status_idx
  on public.mo_records (job_status);

create index if not exists mo_records_type_idx
  on public.mo_records (type);

create index if not exists mo_staging_rows_job_idx
  on public.mo_staging_rows (upload_job_id);

create index if not exists mo_staging_rows_job_row_idx
  on public.mo_staging_rows (upload_job_id, row_number);
