-- Add cleaning-order ACSR schema foundation for hotel CO dashboards.
-- This keeps the module code stable as `co` while leaving room for future cleaning-report variants.

alter type public.module_code add value if not exists 'co';

alter table if exists public.ai_chart_definitions
  drop constraint if exists ai_chart_definitions_module_code_check;

alter table if exists public.ai_chart_definitions
  add constraint ai_chart_definitions_module_code_check
  check ((module_code = any (array['im'::text, 'jo'::text, 'mo'::text, 'co'::text])));

create table if not exists public.co_dashboard_json (
  id uuid default gen_random_uuid() not null primary key,
  organization_id uuid not null,
  upload_job_id uuid not null unique,
  schema_version text not null,
  generated_json jsonb not null,
  generated_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint co_dashboard_json_upload_job_id_fkey
    foreign key (upload_job_id) references public.upload_jobs(id) on delete cascade
);

create table if not exists public.co_records (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  upload_job_id uuid not null,
  uploaded_file_id uuid,
  source_row_id bigint,
  row_key text,
  row_number integer,
  chain_code text,
  hotel_code text,
  module_code text,
  country_code text,
  report_variant text not null default 'ACSR',
  created_date timestamptz,
  cleaning_order_no text,
  room_no text,
  room_type text,
  floor text,
  building text,
  status text,
  status_normalized text,
  priority text,
  priority_normalized text,
  stay_status text,
  attendant text,
  supervisor text,
  department text,
  task_type text,
  cleaning_type text,
  service_round text,
  start_time timestamptz,
  end_time timestamptz,
  completed_time timestamptz,
  duration_minutes numeric,
  planned_duration_minutes numeric,
  actual_duration_minutes numeric,
  duration_variance_minutes numeric,
  ahead_behind_minutes numeric,
  inspection_status text,
  pass_fail text,
  reclean_flag boolean not null default false,
  remarks text,
  created_by text,
  updated_by text,
  updated_on timestamptz,
  cleaning_credit numeric,
  productivity_per_hour numeric,
  is_completed boolean not null default false,
  is_on_time boolean not null default false,
  additional_task_status text,
  type text not null
    constraint co_records_type_check
    check ((type = any (array['MO'::text, 'PM'::text]))),
  normalized_row jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint co_records_upload_job_id_fkey
    foreign key (upload_job_id) references public.upload_jobs(id) on delete cascade,
  constraint co_records_uploaded_file_id_fkey
    foreign key (uploaded_file_id) references public.uploaded_files(id)
);

create table if not exists public.co_staging_rows (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  upload_job_id uuid not null,
  uploaded_file_id uuid not null,
  row_number integer not null,
  raw_row jsonb not null,
  parse_error text,
  is_valid boolean not null default true,
  created_at timestamptz not null default now(),
  constraint co_staging_rows_upload_job_id_fkey
    foreign key (upload_job_id) references public.upload_jobs(id) on delete cascade,
  constraint co_staging_rows_uploaded_file_id_fkey
    foreign key (uploaded_file_id) references public.uploaded_files(id) on delete cascade
);

create index if not exists co_dashboard_json_created_idx
  on public.co_dashboard_json (created_at);

create index if not exists co_dashboard_json_job_idx
  on public.co_dashboard_json (upload_job_id);

create index if not exists co_records_attendant_idx
  on public.co_records (attendant);

create index if not exists co_records_row_key_idx
  on public.co_records (row_key);

create index if not exists co_records_building_idx
  on public.co_records (building);

create index if not exists co_records_created_date_idx
  on public.co_records (created_date);

create index if not exists co_records_floor_idx
  on public.co_records (floor);

create index if not exists co_records_job_idx
  on public.co_records (upload_job_id);

create index if not exists co_records_room_no_idx
  on public.co_records (room_no);

create index if not exists co_records_row_number_idx
  on public.co_records (row_number);

create index if not exists co_records_scope_idx
  on public.co_records (chain_code, hotel_code, module_code, country_code, report_variant);

create index if not exists co_records_status_idx
  on public.co_records (status_normalized);

create index if not exists co_records_type_idx
  on public.co_records (type);

create index if not exists co_records_priority_idx
  on public.co_records (priority_normalized);

create index if not exists co_staging_rows_job_idx
  on public.co_staging_rows (upload_job_id);

create index if not exists co_staging_rows_job_row_idx
  on public.co_staging_rows (upload_job_id, row_number);
