-- Cleaning Order Inspection Report (CO-IR) records.
-- Kept separate from CO-ACSR so either report can be replaced independently.

create table if not exists public.co_ir_records (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  upload_job_id uuid not null,
  uploaded_file_id uuid,
  source_row_id bigint,
  row_key text,
  row_number integer,
  chain_code text,
  hotel_code text,
  module_code text not null default 'co',
  country_code text,
  report_variant text not null default 'IR' check (report_variant = 'IR'),
  inspection_date date,
  inspector text,
  location text,
  start_time timestamptz,
  complete_time timestamptz,
  cleaned_by text,
  turn_over_minutes numeric,
  inspection_duration_minutes numeric,
  duration_source text check (duration_source in ('TIMESTAMP_DIFF', 'TURN_OVER_TIME')),
  inspection_result text,
  inspection_score numeric,
  room_status text,
  inspection_credit numeric,
  normalized_row jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint co_ir_records_upload_job_id_fkey
    foreign key (upload_job_id) references public.upload_jobs(id) on delete cascade,
  constraint co_ir_records_uploaded_file_id_fkey
    foreign key (uploaded_file_id) references public.uploaded_files(id)
);

create index if not exists co_ir_records_scope_idx
  on public.co_ir_records (chain_code, hotel_code, inspection_date);
create index if not exists co_ir_records_job_idx
  on public.co_ir_records (upload_job_id);
create index if not exists co_ir_records_inspector_idx
  on public.co_ir_records (inspector);
create index if not exists co_ir_records_room_status_idx
  on public.co_ir_records (room_status);
create index if not exists co_ir_records_location_idx
  on public.co_ir_records (location);
create index if not exists co_ir_records_result_idx
  on public.co_ir_records (inspection_result);
